### ISSUE TITLE
In V3 Gate.js is missing

### ISSUE THREAD

**Issue by abramhindle** [gibber-cc/gibberish#19]
Please git add js/fx/gate.js to the repo.

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by charlieroberts** [comment]
It's actually not ready to push yet; I accidentally included it in effects.js when I shouldn't have. I suppose that now I've switched to v3 as the default branch I should setup a v3_develop branch for such things, or just start being more aggressive with branch creation more generally.

I removed the inclusion of gate.js from effects.js in commit 8efbb7d.
