### ISSUE TITLE
Not able to use Gibberish.Sampler()

### ISSUE THREAD

**Issue by vasuki1996** [gibber-cc/gibberish#23]
its giving me Gibberish.Sampler is not a constructor error.
Im not able to figure out what is the issue
here's the code
sampler = new Gibberish.Sampler({
                file: "assets/media/MOE.mp3",
                loops:true,
                playOnLoad:1,
            });

**Comment by charlieroberts** [comment]
Sorry for the delayed response... in the new (3.0) version of Gibberish you don't need to use the `new` keyword in front of `Gibberish.Sampler`, although it seems very strange that this would thrown an error. Does it work if you remove the `new` keyword?

**Comment by charlieroberts** [comment]
For example, the following code works fine in the playground:

```javascript
rhodes = Sampler({
  filename:'http://charlie-roberts.com/gibberish/playground/resources/audiofiles/rhodes.wav',
  loops:true
}).connect()
```
